import{i as l,S as f}from"./assets/vendor-5ObWk2rO.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&i(o)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const m="46197993-0238acfcd6230053ff5f60fb7",u="https://pixabay.com/api/";document.addEventListener("DOMContentLoaded",()=>{const c=document.getElementById("search-form"),s=document.querySelector(".search-input"),n=document.querySelector(".gallery");c.addEventListener("submit",async i=>{i.preventDefault();const e=s.value.trim();if(!e){l.error({title:"Error",message:"Please enter a search query."});return}n.innerHTML="";const t=document.querySelector(".loader");t.style.display="block";try{const d=await(await fetch(`${u}?key=${m}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true`)).json();if(t.style.display="none",d.hits.length===0){l.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"});return}d.hits.forEach(r=>{const a=document.createElement("div");a.classList.add("gallery-item"),a.innerHTML=`
                    <a href="${r.largeImageURL}" class="gallery-link">
                        <img src="${r.webformatURL}" alt="${r.tags}" class="gallery-image" />
                    </a>
                    <div class="info">
                        <p class="info-item"><b>Likes</b> ${r.likes}</p>
                        <p class="info-item"><b>Views</b> ${r.views}</p>
                        <p class="info-item"><b>Comments</b> ${r.comments}</p>
                        <p class="info-item"><b>Downloads</b> ${r.downloads}</p>
                    </div>
                `,n.appendChild(a)}),new f(".gallery-link",{}).refresh()}catch(o){t.style.display="none",l.error({title:"Error",message:"Failed to fetch images. Please try again."}),console.error("Error:",o)}})});
//# sourceMappingURL=index.js.map
